// <auto-generated />
namespace TDM.SysCRM.AcessoADados.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ConsultorEntidade : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ConsultorEntidade));
        
        string IMigrationMetadata.Id
        {
            get { return "201807071402070_ConsultorEntidade"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
